# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: GH Pages deploy
      # You may pin to the exact commit or the version.
      # uses: Cecilapp/GitHub-Pages-deploy@a6f0cf12a4874fbeb75f6393d0568fb3c86dda37
      uses: Cecilapp/GitHub-Pages-deploy@3.2.0
      with:
        email: szymonrykala@gmail.com
        build_dir: ./build
        branch: gh-pages
        commit_message: deploy
